# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManorGui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 557)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.Main = QtWidgets.QTabWidget(self.central_widget)
        self.Main.setGeometry(QtCore.QRect(0, 0, 771, 511))
        self.Main.setObjectName("Main")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.main_frame = QtWidgets.QFrame(self.tab)
        self.main_frame.setGeometry(QtCore.QRect(0, -2, 769, 491))
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.run = QtWidgets.QPushButton(self.main_frame)
        self.run.setGeometry(QtCore.QRect(40, 340, 151, 41))
        self.run.setObjectName("run")
        self.rel_con = QtWidgets.QPushButton(self.main_frame)
        self.rel_con.setGeometry(QtCore.QRect(250, 340, 151, 41))
        self.rel_con.setObjectName("rel_con")
        self.exp = QtWidgets.QPushButton(self.main_frame)
        self.exp.setGeometry(QtCore.QRect(460, 340, 151, 41))
        self.exp.setObjectName("exp")
        self.mquit = QtWidgets.QPushButton(self.main_frame)
        self.mquit.setGeometry(QtCore.QRect(590, 410, 151, 41))
        self.mquit.setObjectName("mquit")
        self.main_param_frame = QtWidgets.QFrame(self.main_frame)
        self.main_param_frame.setGeometry(QtCore.QRect(20, 70, 301, 231))
        self.main_param_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_param_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_param_frame.setObjectName("main_param_frame")
        self.mipl_abel = QtWidgets.QLabel(self.main_param_frame)
        self.mipl_abel.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.mipl_abel.setTextFormat(QtCore.Qt.AutoText)
        self.mipl_abel.setObjectName("mipl_abel")
        self.mport_label = QtWidgets.QLabel(self.main_param_frame)
        self.mport_label.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.mport_label.setObjectName("mport_label")
        self.mpayload_label = QtWidgets.QLabel(self.main_param_frame)
        self.mpayload_label.setGeometry(QtCore.QRect(20, 120, 111, 31))
        self.mpayload_label.setObjectName("mpayload_label")
        self.mtimer_label = QtWidgets.QLabel(self.main_param_frame)
        self.mtimer_label.setGeometry(QtCore.QRect(20, 180, 111, 31))
        self.mtimer_label.setObjectName("mtimer_label")
        self.mport_text = QtWidgets.QLineEdit(self.main_param_frame)
        self.mport_text.setGeometry(QtCore.QRect(160, 70, 121, 25))
        self.mport_text.setObjectName("mport_text")
        self.mpayload_text = QtWidgets.QLineEdit(self.main_param_frame)
        self.mpayload_text.setGeometry(QtCore.QRect(160, 120, 121, 25))
        self.mpayload_text.setObjectName("mpayload_text")
        self.mtimer_text = QtWidgets.QLineEdit(self.main_param_frame)
        self.mtimer_text.setGeometry(QtCore.QRect(160, 180, 121, 25))
        self.mtimer_text.setObjectName("mtimer_text")
        self.mip_text = QtWidgets.QLineEdit(self.main_param_frame)
        self.mip_text.setGeometry(QtCore.QRect(160, 20, 121, 25))
        self.mip_text.setObjectName("mip_text")
        self.main_label = QtWidgets.QLabel(self.main_frame)
        self.main_label.setGeometry(QtCore.QRect(20, 20, 121, 31))
        self.main_label.setObjectName("main_label")
        self.Main.addTab(self.tab, "")
        self.Status = QtWidgets.QWidget()
        self.Status.setObjectName("Status")
        self.status_frame = QtWidgets.QFrame(self.Status)
        self.status_frame.setGeometry(QtCore.QRect(0, -2, 779, 491))
        self.status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.status_frame.setObjectName("status_frame")
        self.progress_bar = QtWidgets.QProgressBar(self.status_frame)
        self.progress_bar.setGeometry(QtCore.QRect(90, 360, 541, 31))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.sstatus_label = QtWidgets.QLabel(self.status_frame)
        self.sstatus_label.setGeometry(QtCore.QRect(20, 20, 121, 31))
        self.sstatus_label.setObjectName("sstatus_label")
        self.param_frame = QtWidgets.QFrame(self.status_frame)
        self.param_frame.setGeometry(QtCore.QRect(20, 100, 331, 231))
        self.param_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.param_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.param_frame.setObjectName("param_frame")
        self.siplabel = QtWidgets.QLabel(self.param_frame)
        self.siplabel.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.siplabel.setObjectName("siplabel")
        self.spaylod_label = QtWidgets.QLabel(self.param_frame)
        self.spaylod_label.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.spaylod_label.setObjectName("spaylod_label")
        self.stime_label = QtWidgets.QLabel(self.param_frame)
        self.stime_label.setGeometry(QtCore.QRect(10, 180, 111, 31))
        self.stime_label.setObjectName("stime_label")
        self.sip_text = QtWidgets.QLabel(self.param_frame)
        self.sip_text.setGeometry(QtCore.QRect(120, 30, 111, 31))
        self.sip_text.setAutoFillBackground(False)
        self.sip_text.setObjectName("sip_text")
        self.sport_text = QtWidgets.QLabel(self.param_frame)
        self.sport_text.setGeometry(QtCore.QRect(120, 80, 111, 31))
        self.sport_text.setObjectName("sport_text")
        self.spayload_text = QtWidgets.QLabel(self.param_frame)
        self.spayload_text.setGeometry(QtCore.QRect(120, 130, 111, 31))
        self.spayload_text.setObjectName("spayload_text")
        self.slabel_text = QtWidgets.QLabel(self.param_frame)
        self.slabel_text.setGeometry(QtCore.QRect(120, 180, 111, 31))
        self.slabel_text.setObjectName("slabel_text")
        self.sport_label = QtWidgets.QLabel(self.param_frame)
        self.sport_label.setGeometry(QtCore.QRect(10, 80, 101, 31))
        self.sport_label.setObjectName("sport_label")
        self.clear_all = QtWidgets.QPushButton(self.status_frame)
        self.clear_all.setGeometry(QtCore.QRect(638, 60, 91, 25))
        self.clear_all.setObjectName("clear_all")
        self.app_log_text = QtWidgets.QTextBrowser(self.status_frame)
        self.app_log_text.setGeometry(QtCore.QRect(420, 100, 311, 231))
        self.app_log_text.setObjectName("app_log_text")
        self.app_log_label = QtWidgets.QLabel(self.status_frame)
        self.app_log_label.setGeometry(QtCore.QRect(420, 60, 81, 21))
        self.app_log_label.setObjectName("app_log_label")
        self.squit = QtWidgets.QPushButton(self.status_frame)
        self.squit.setGeometry(QtCore.QRect(590, 410, 151, 41))
        self.squit.setObjectName("squit")
        self.sparam_label = QtWidgets.QLabel(self.status_frame)
        self.sparam_label.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.sparam_label.setObjectName("sparam_label")
        self.Main.addTab(self.Status, "")
        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 771, 22))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_file = QtWidgets.QMenu(self.menu_bar)
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menu_bar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.action_run = QtWidgets.QAction(MainWindow)
        self.action_run.setObjectName("action_run")
        self.action_rel_con = QtWidgets.QAction(MainWindow)
        self.action_rel_con.setObjectName("action_rel_con")
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setObjectName("action_export")
        self.action_clear_all = QtWidgets.QAction(MainWindow)
        self.action_clear_all.setObjectName("action_clear_all")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menu_file.addAction(self.action_run)
        self.menu_file.addAction(self.action_rel_con)
        self.menu_file.addAction(self.action_export)
        self.menu_file.addAction(self.action_clear_all)
        self.menu_file.addAction(self.action_quit)
        self.menu_help.addAction(self.action_about)
        self.menu_bar.addAction(self.menu_file.menuAction())
        self.menu_bar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.Main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p>Manor User Interface</p></body></html>"))
        self.run.setToolTip(_translate("MainWindow", "<html><head/><body><p>Runs function with given parameters. Don\'t forget to reload config before running.</p></body></html>"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.rel_con.setToolTip(_translate("MainWindow", "<html><head/><body><p>Sets changed values to the existing parameters.</p></body></html>"))
        self.rel_con.setText(_translate("MainWindow", "Reload Config"))
        self.exp.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exports the output of the function to a file.</p></body></html>"))
        self.exp.setText(_translate("MainWindow", "Export"))
        self.mquit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Quits application.</p></body></html>"))
        self.mquit.setText(_translate("MainWindow", "Quit"))
        self.mipl_abel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">IP Adress</span></p></body></html>"))
        self.mport_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Port</span></p><p><br/></p></body></html>"))
        self.mpayload_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Payload</span></p></body></html>"))
        self.mtimer_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Timer</span></p></body></html>"))
        self.mport_text.setText(_translate("MainWindow", "8080"))
        self.mport_text.setPlaceholderText(_translate("MainWindow", "Enter port..."))
        self.mpayload_text.setText(_translate("MainWindow", "\'a, b, c, d\'"))
        self.mpayload_text.setPlaceholderText(_translate("MainWindow", "Enter payload..."))
        self.mtimer_text.setText(_translate("MainWindow", "10"))
        self.mtimer_text.setPlaceholderText(_translate("MainWindow", "Enter timer..."))
        self.mip_text.setText(_translate("MainWindow", "10.0.0.1"))
        self.mip_text.setPlaceholderText(_translate("MainWindow", "Enter IP..."))
        self.main_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Main:</span></p><p><br/></p></body></html>"))
        self.Main.setTabText(self.Main.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.sstatus_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Status:</span></p></body></html>"))
        self.siplabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">IP Adress:</span></p></body></html>"))
        self.spaylod_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Payload:</span></p></body></html>"))
        self.stime_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Timer:</span></p></body></html>"))
        self.sip_text.setText(_translate("MainWindow", "TextLabel"))
        self.sport_text.setText(_translate("MainWindow", "TextLabel"))
        self.spayload_text.setText(_translate("MainWindow", "TextLabel"))
        self.slabel_text.setText(_translate("MainWindow", "TextLabel"))
        self.sport_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Port:</span></p></body></html>"))
        self.clear_all.setText(_translate("MainWindow", "Clear All"))
        self.app_log_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">App Log:</span></p></body></html>"))
        self.squit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Quits application.</p></body></html>"))
        self.squit.setText(_translate("MainWindow", "Quit"))
        self.sparam_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Parameters:</span></p></body></html>"))
        self.Main.setTabText(self.Main.indexOf(self.Status), _translate("MainWindow", "Tab 2"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.action_run.setText(_translate("MainWindow", "Run"))
        self.action_run.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_rel_con.setText(_translate("MainWindow", "Reload Config"))
        self.action_rel_con.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_export.setText(_translate("MainWindow", "Export"))
        self.action_export.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_clear_all.setText(_translate("MainWindow", "Clear All"))
        self.action_clear_all.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_quit.setText(_translate("MainWindow", "Quit"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_about.setText(_translate("MainWindow", "About"))
        self.action_about.setShortcut(_translate("MainWindow", "Ctrl+I"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
